import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Payment Integration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my shop!</h1>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <Image
              src="/images/picture1.png"
              alt="product"
              width={400}
              height={300}
            />
            <p>This is the clothing set 1</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <Image
              src="/images/picture2.png"
              alt="product"
              width={400}
              height={300}
            />
            <p>This is the clothing set 2</p>
          </a>
        </div>
      </main>
    </div>
  );
}
